Initial docs for GPU support
omnivector-solutions/osd-documentation pull request #63
Opened 2022-02-14 21:13 UTC by heitorPB

2022-02-17 22:43 UTC, dusktreader requested changes
Couple of suggestions for you.

2022-02-17 22:43 UTC, dusktreader commented on operations/gpu.rst
> +After installing GPU Drivers, one should reboot them. Check
```suggestion
After installing GPU Drivers, you should reboot the nodes using them. Check
```

2022-02-18 13:16 UTC, heitorPB commented on operations/gpu.rst
> +OSD supports installing GPU drivers for the compute nodes via a set of Juju
Is this a grammar issue? In Portuguese, it is recommended to avoid your suggestion, but this may not apply for English...

2022-02-18 17:02 UTC, matheushent commented on operations/gpu.rst
> +OSD supports installing GPU drivers for the compute nodes via a set of Juju
I guess `ing` is only applied to verbs when prepositions are first. Correct me if I am wrong

2022-02-18 18:51 UTC, dusktreader commented on operations/gpu.rst
> +OSD supports installing GPU drivers for the compute nodes via a set of Juju
It's not grammatically incorrect. I think it reads more naturally, though.

2022-02-21 21:06 UTC, jamesbeedy commented
100% - Nice - 👍

2022-02-25 18:28 UTC, merged